HR

--CONSULTAS CON CADENAS DE TEXTO
--1
SELECT LOWER((FIRST_NAME || ' ' || LAST_NAME)) AS nombre FROM EMPLOYEES e ;

--2
SELECT UPPER(CONCAT(FIRST_NAME, LAST_NAME)) AS nombre FROM EMPLOYEES e ;

--3
SELECT DECODE(manager_id, NULL,
UPPER(e.FIRST_name ||' '|| e.last_name),
LOWER(e.first_name|| ' '|| e.last_name))
FROM EMPLOYEES e;

--4
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES e ;

--5
SELECT (FIRST_NAME || ' ' || last_Name) AS nombre,LOWER(RPAD(EMAIL,12,'*')) FROM
EMPLOYEES e ;

--6
SELECT FIRST_NAME, LENGTH(FIRST_NAME),
(SUBSTR(LAST_NAME,1,2)||SUBSTR(PHONE_NUMBER,1,3)||SUBSTR(FIRST_NAME,-2)) AS
contrasena FROM EMPLOYEES e ;


--CONSULTA CON FECHAS
--7
SELECT start_date,TO_CHAR(START_DATE,'DD'), TO_CHAR(START_DATE,'MM'),
TO_CHAR(START_DATE,'YYYY') FROM JOB_HISTORY jh;

--8
SELECT START_DATE, ROUND(SYSDATE-START_DATE,2) ,
ROUND(MONTHS_BETWEEN(SYSDATE,START_DATE),2) FROM JOB_HISTORY jh ;


--CONSULTA CON NUMEROS
--9 SIN ACABAR
SELECT FIRST_NAME , JOB_ID, ROUND(SALARY,2) , TRUNC((SALARY*12),1) FROM
EMPLOYEES e ;

--10
SELECT FIRST_NAME , LAST_NAME, CASE
WHEN substr(LAST_NAME,1,1)='K' THEN (SALARY+ (salary*0.1))
ELSE salary
END AS salario
FROM EMPLOYEES e ;


--CONSULTAS ORDENADAS CON FILTROS
--11
SELECT * FROM EMPLOYEES e ORDER BY HIRE_DATE ;

--12
SELECT * FROM EMPLOYEES e WHERE EMPLOYEE_ID =109;

--13
SELECT * FROM EMPLOYEES e WHERE JOB_ID = 'AD_VP';

--14
SELECT * FROM EMPLOYEES e WHERE (e.HIRE_DATE<TO_DATE('01/01/2006','dd/mm/yyyy'));

--15
SELECT * FROM EMPLOYEES e WHERE ((JOB_ID='IT_PROG')AND(SALARY<5000));

--16
SELECT CASE MANAGER_ID WHEN NULL THEN (first_name || ' '|| last_name)
ELSE lower (first_name || ' '|| last_name)
END nombre_completo
FROM EMPLOYEES e WHERE SUBSTR(phone_number,1,3)=650 ;

--17
SELECT * FROM EMPLOYEES e WHERE
((TO_CHAR(HIRE_DATE,'MM')='06')OR(TO_CHAR(HIRE_DATE,'MM')='07')OR(TO_CHAR(HIRE_D
ATE,'MM')='08')) ORDER BY SALARY ;

--18
SELECT * FROM EMPLOYEES e WHERE ((LAST_NAME LIKE '%w%') OR(LAST_NAME LIKE
'%W%')) ORDER BY FIRST_NAME DESC ;

--19
SELECT * FROM EMPLOYEES e WHERE MANAGER_ID IS NULL ;

--20
SELECT (FIRST_NAME || ' ' || last_Name) AS nombre,LOWER(RPAD(EMAIL,12,'*')) FROM
EMPLOYEES e WHERE SALARY BETWEEN 10000 AND 20000;

--21
SELECT * FROM EMPLOYEES e WHERE
((JOB_ID='IT_PROG')OR(JOB_ID='SA_REP')OR(JOB_ID='FI_ACCOUNT'));

--22
SELECT * FROM EMPLOYEES e WHERE ((SALARY BETWEEN 10000 AND
20000)AND((JOB_ID='IT_PROG')OR(JOB_ID='SA_REP')OR(JOB_ID='FI_ACCOUNT')));

--23
SELECT * FROM EMPLOYEES e WHERE ((SALARY BETWEEN 10000 AND 20000)OR
((JOB_ID='IT_PROG')OR(JOB_ID='SA_REP')OR(JOB_ID='FI_ACCOUNT')));

--24
SELECT * FROM EMPLOYEES e WHERE ((PHONE_NUMBER LIKE '515%')OR(PHONE_NUMBER
LIKE '011%')) ;

--25
SELECT FIRST_NAME , JOB_ID, ROUND(SALARY,2) , TRUNC((SALARY*12),1) FROM
EMPLOYEES e WHERE ((JOB_ID='ST_CLERK')AND((MANAGER_ID='122')OR(SALARY<3000)));

--26
SELECT FIRST_NAME, LENGTH(FIRST_NAME),
(SUBSTR(LAST_NAME,1,2)||SUBSTR(PHONE_NUMBER,1,3)||SUBSTR(FIRST_NAME,-2)) AS
contrasena FROM EMPLOYEES e WHERE ((FIRST_NAME LIKE 'A%')OR(FIRST_NAME LIKE
'B%')OR(FIRST_NAME LIKE 'S%')OR(FIRST_NAME LIKE 'N%'));

--27
SELECT * FROM EMPLOYEES e WHERE LENGTH(e.FIRST_NAME)=5 ORDER BY FIRST_NAME
DESC ;

--28
SELECT * FROM EMPLOYEES e WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE )>(20*12);

--29
SELECT * FROM EMPLOYEES e WHERE (PHONE_NUMBER LIKE '%423%');

--30
SELECT DISTINCT salary FROM EMPLOYEES e ORDER BY SALARY DESC ;
