multas

--1
SELECT p.NOMBRE FROM PERSONAS p ;

--2
SELECT NOMBRE , DNI FROM PERSONAS p ;

--3
SELECT MATRICULA coche, IMPORTE multa_euros, (IMPORTE*1.02) multa_dolares FROM
MULTAS m ;

--4
SELECT LOWER(NOMBRE) nombre_persona, DNI FROM PERSONAS p ;

--5
SELECT NOMBRE , SUBSTR(DNI,1,4) AS codigo_persona FROM PERSONAS p ;

--6
SELECT NOMBRE , SUBSTR(DNI, 7,9) AS codigo_persona FROM PERSONAS p ;

--7
SELECT MATRICULA , IMPORTE , (IMPORTE*0.5) importe_bonificado FROM MULTAS m ;

--8
SELECT MATRICULA , IMPORTE , ROUND(IMPORTE*0.5,1) importe_bonificado_redondeado
FROM MULTAS m ;

--9
SELECT MATRICULA , IMPORTE , TRUNC(IMPORTE*0.5,1) importe_bonificado_redondeado
FROM MULTAS m ;

--10
SELECT DNI FROM MATRICULAS m ;

--11
SELECT DISTINCT DNI FROM MATRICULAS m ;

--12
SELECT NOMBRE FROM PERSONAS p ORDER BY NOMBRE ;

--13
SELECT NOMBRE FROM PERSONAS p ORDER BY NOMBRE DESC ;

--14
SELECT IMPORTE ,LUGAR FROM MULTAS m ORDER BY IMPORTE DESC , LUGAR ASC ;

--15
SELECT NOMBRE FROM PERSONAS p WHERE rownum < 6;

--16
SELECT * FROM MULTAS m WHERE MATRICULA = '6981-BMN' ;

--17
SELECT * FROM MATRICULAS m WHERE DNI= '451256522T';
SELECT * FROM MULTAS m WHERE MATRICULA = '6578-BJS'OR MATRICULA='A-5782-BK';

--18
SELECT * FROM PERSONAS p WHERE NOMBRE = 'DORIS, MICHAEL' ;
SELECT * FROM MATRICULAS m WHERE DNI= '120365879U';
SELECT * FROM MULTAS m WHERE MATRICULA = '1206-DBN';

--19
SELECT * FROM MULTAS m WHERE IMPORTE > 300;

--20
SELECT * FROM MULTAS m WHERE IMPORTE <100;

--21
SELECT * FROM MULTAS m WHERE IMPORTE >= 150 AND IMPORTE <=350;
SELECT * FROM MULTAS m WHERE IMPORTE BETWEEN 150 AND 350;

--22
SELECT * FROM MULTAS m WHERE IMPORTE = 50 OR IMPORTE =100 OR IMPORTE=200;
--falta la segunda manera

--23
SELECT * FROM PERSONAS p WHERE SUBSTR(NOMBRE,1,1)='R';

--24
SELECT * FROM PERSONAS p WHERE SUBSTR(NOMBRE,1,1)='G' OR
SUBSTR(NOMBRE,1,1)='F';

--25
SELECT * FROM PERSONAS p WHERE SUBSTR(NOMBRE,1,2) = 'DO';

--26
SELECT * FROM PERSONAS p WHERE INSTR(NOMBRE, 'CIA')>0 ;
SELECT * FROM PERSONAS p WHERE NOMBRE LIKE '%_CIA_%';

--27
SELECT * FROM PERSONAS p WHERE NOMBRE LIKE '%_AN';
