SELECT * FROM DETALLE_PEDIDOS dp ;
SELECT * FROM PEDIDOS p ;
SELECT * FROM COMP_ENVIO ce ;
SELECT * FROM PRODUCTOS p ;
SELECT *FROM CLIENTES c ;
SELECT * FROM CATEGORIAS c ;
SELECT * FROM PROVEEDORES p ;
SELECT * FROM EMPLEADOS e ;


--9 
SELECT p.NOMBRE AS proveedor , p2.NOMBRE AS producto, p2.PRECIOXUNIDAD 
FROM PROVEEDORES p 
	JOIN PRODUCTOS p2 ON p2.IDPROVEEDOR =p.IDPROVEEDOR 
WHERE (p2.PRECIOXUNIDAD, p.NOMBRE) IN (SELECT min(p3.precioxunidad), p4.nombre
										FROM PROVEEDORES p4 
										JOIN PRODUCTOS p3 ON p3.IDPROVEEDOR =p4.IDPROVEEDOR
										GROUP BY p4.nombre) ;
										
--3
SELECT DISTINCT c.NOMBRE
FROM CLIENTES c 
	JOIN PEDIDOS p ON p.IDCLIENTE = c.IDCLIENTE 
	JOIN DETALLE_PEDIDOS dp ON dp.IDPEDIDO = p.IDPEDIDO 
	JOIN PRODUCTOS pr ON pr.IDPRODUCTO = dp.IDPRODUCTO  
WHERE p.IDPEDIDO NOT IN (SELECT p2.IDPEDIDO 
							FROM PEDIDOS p2
								JOIN DETALLE_PEDIDOS dp2 ON dp2.IDPEDIDO = p2.IDPEDIDO 
								JOIN PRODUCTOS pr2 ON pr2.IDPRODUCTO = dp2.IDPRODUCTO
							WHERE pr2.IDCATEGORIA = 3 );

--5
SELECT c.NOMBRE, p.FECHAPEDIDO , p.DESTINATARIO 
FROM CLIENTES c 
	left JOIN PEDIDOS p ON p.IDCLIENTE = c.IDCLIENTE 
ORDER BY 1; 
	

--11 
SELECT c.PAIS, COUNT(dp.IDPRODUCTO), SUM((dp.PRECIOXUNIDAD*dp.CANTIDAD)-dp.DESCUENTO)  
FROM CLIENTES c
	JOIN PEDIDOS p ON p.IDCLIENTE = c.IDCLIENTE 
	JOIN DETALLE_PEDIDOS dp ON dp.IDPEDIDO = p.IDPEDIDO 
GROUP BY c.PAIS 
HAVING c.pais IN (SELECT c2.pais
		FROM CLIENTES c2
		GROUP BY c2.PAIS
		HAVING COUNT(c2.IDCLIENTE)>1);
	
--4
SELECT p.NOMBRE , ROUND(AVG(dp.CANTIDAD),1), MIN(pe.FECHAPEDIDO)  
FROM PRODUCTOS p 
	JOIN DETALLE_PEDIDOS dp ON dp.IDPRODUCTO = p.IDPRODUCTO 
	JOIN PEDIDOS pe ON pe.IDPEDIDO = dp.IDPEDIDO 
GROUP BY p.NOMBRE 
	

--6
SELECT COUNT(*)
FROM PRODUCTOS p 
WHERE p.EXISTENCIAS >100;

--10
SELECT c.PAIS, c.CIUDAD , COUNT(p.CARGO) AS total_cargos 
FROM CLIENTES c 
JOIN PEDIDOS p ON p.IDCLIENTE = c.IDCLIENTE 
GROUP BY c.PAIS, c.CIUDAD
ORDER BY c.PAIS ASC, total_cargos DESC  ;

--1
SELECT p.NOMBRE , p.EXISTENCIAS , p.PRECIOXUNIDAD 
FROM PRODUCTOS p 
WHERE (p.EXISTENCIAS >100) AND (p.PRECIOXUNIDAD<15) ;

--7 
SELECT c.NOMBRE , p.FECHAPEDIDO , p.FECHAENTREGA 
FROM CLIENTES c 
JOIN PEDIDOS p ON p.IDCLIENTE = c.IDCLIENTE 
WHERE (TO_CHAR(p.FECHAPEDIDO, 'mm') IN (1,2,3))
		AND 
	(p.FECHAENTREGA-p.FECHAPEDIDO)<16;

--2
(SELECT DISTINCT  c.NOMBRE, 'S' AS pedidos				
FROM CLIENTES c 
	JOIN PEDIDOS p ON p.IDCLIENTE =c.IDCLIENTE)
UNION 
(SELECT c2.NOmbre, 'N' AS pedidos
FROM CLIENTES c2
	left JOIN PEDIDOS p2 ON p2.IDCLIENTE = c2.IDCLIENTE 
WHERE p2.idpedido IS  NULL)
;


		
--8   :(
SELECT TO_CHAR(p.FECHAPEDIDO, 'yyyy') 
FROM PEDIDOS p 
	JOIN DETALLE_PEDIDOS dp ON dp.IDPEDIDO =p.IDPEDIDO 
	GROUP BY TO_CHAR(p.FECHAPEDIDO, 'yyyy')
HAVING  TO_CHAR(p.FECHAPEDIDO, 'yyyy') IN

											(SELECT TO_CHAR(p2.FECHAPEDIDO, 'yyyy')
											FROM PEDIDOS p2 
												JOIN DETALLE_PEDIDOS dp2 ON dp2.IDPEDIDO =p2.IDPEDIDO 
												JOIN PRODUCTOS pr2 ON pr2.idproducto= dp2.idproducto
											GROUP BY TO_CHAR(p2.FECHAPEDIDO, 'yyyy'), pr2.idcategoria
											having SUM((dp2.PRECIOXUNIDAD*dp2.CANTIDAD)-dp2.DESCUENTO) > 200000
													AND pr2.idcategoria !=1);

	

SELECT * FROM DETALLE_PEDIDOS dp ;
SELECT * FROM PEDIDOS p ;
SELECT * FROM COMP_ENVIO ce ;
SELECT * FROM PRODUCTOS p ;
SELECT *FROM CLIENTES c ;
SELECT * FROM CATEGORIAS c ;
SELECT * FROM PROVEEDORES p ;
SELECT * FROM EMPLEADOS e ;
